title: "<div class='first-name'>CONNOR</div><div class='last-name'>NISHIJIMA</div>"
description: Embedded C/C++ Engineer
theme: just-the-docs

url: https://connor.nishiji.ma

color_scheme: connor

aux_links:
  "HIRE ME":
    - "<link-out>https://www.linkedin.com/in/connornishijima</link-out>"

# External navigation links
nav_external_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/connornishijima
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: Mastodon
    url: https://leds.social/@lixielabs
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: Threads
    url: https://threads.net/@lixielabs
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
