title: Connor Nishijima
description: Embedded C/C++ Engineer
theme: just-the-docs

url: https://connor.nishiji.ma

color_scheme: connor

favicon_ico: "/favicon.ico"

plugins:
  - jekyll-sitemap

collections:
  products:
    output: true
  works:
    output: true

just_the_docs:
  collections:
    products:
      name: Products I've Designed
    works:
      name: Highlighted Works

callouts:
  warning:
    title: WATCH OUT!
    color: red
  highlight:
    title: PLEASE NOTE
    color: yellow
  info:
    title: JUST SO YOU KNOW
    color: grey-dk
  glow:
    title:  
    color: grey-dk

compress_html:
  blanklines: true

aux_links:
  "<link-out>HIRE ME</link-out>":
    - https://www.linkedin.com/in/connornishijima

# External navigation links
nav_external_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/connornishijima/details/experience/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: YouTube
    url: https://www.youtube.com/@lixielabs/videos
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: GitHub
    url: https://www.github.com/connornishijima
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  